apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    function: kubecost-tunnel
    party: falkonry
  name: kubecost-tunnel
  namespace: '{{.Values.namespace}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubecost-tunnel
  template:
    metadata:
      labels:
        function: kubecost
        name: kubecost-tunnel
        party: falkonry
    spec:
      containers:
        - command:
            - sh
            - /run.sh
          env:
            - name: NAMESPACE
              value: "falkonry"
            - name: DEPLOYMENT
              value: "cost-analyzer"
            - name: FWD_PORT
              value: "9091"
            - name: REMOTE_PORT
              value: "9090"              
          image: quay.io/falkonry/docker-ssh-tunnel:latest
          imagePullPolicy: Always
          name: kubecost-tunnel
          ports:
            - containerPort: 9091
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - mountPath: "/root/.kube"
              name: kubeconfig
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubecost-tunnel-secret
            defaultMode: 0600
